Fix pyarrow/parquet deps in DPS env
Add conda lock file to pin all dependencies in order to fix the
following import error:

    ImportError: Missing optional dependency 'pyarrow.parquet'.